#!/bin/bash
source $(dirname $0)/d-conf

n=$(($1 + 4))
PERC=`mpstat -P ALL 0 | awk '{gsub(//,""); print $4}' | sed -n "$n"p`

ICON="cpu.xbm"
if [[ $PERC > 75 ]]; then
PERCBAR=`echo -e "$PERC"\
	| gdbar -bg $bar_bg -fg $warning -h 1 -w 115`
else
PERCBAR=`echo -e "$PERC"\
	| gdbar -bg $bar_bg -fg $foreground -h 1 -w 115`
fi

echo "^fg($FG2) ⮦ CPU$1^fg() $PERCBAR ^fg($highlight)$PERC%"
